#
# version.cmake : version du projet
#

set (QUALIF_MAJOR_VERSION "2")
set (QUALIF_MINOR_VERSION "3")
set (QUALIF_RELEASE_VERSION "5")
set (QUALIF_VERSION ${QUALIF_MAJOR_VERSION}.${QUALIF_MINOR_VERSION}.${QUALIF_RELEASE_VERSION})
